version: "3"

services:
  app:
    build: .
    restart: always
    depends_on:
      - redis
    ports:
      - "8080:8080"

  redis:
    image: redis
    command:
      - redis-server
    ports:
      - "6379:6379"